services:
  frontend:
    image: dhruv2k3/basal-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - basal-net
  backend:
    image: dhruv2k3/basal-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - basal-net
  ml-server:
    image: dhruv2k3/basal-ml-server:latest
    container_name: ml-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - basal-net
networks:
  basal-net:
    driver: bridge
