services:
  frontend:
    image: dhruv2k3/biasbreaker-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - biasbreaker-net
  backend:
    image: dhruv2k3/biasbreaker-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - biasbreaker-net
  ml-server:
    image: dhruv2k3/biasbreaker-ml-server:latest
    container_name: ml-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - biasbreaker-net
networks:
  biasbreaker-net:
    driver: bridge